name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '18-ea'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
           name: apk
           path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Release apk
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download apk
        uses: actions/download-artifact@v3
        with:
          name: apk
      - name: Test download
        run: ls -R
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          replacesArtifacts: true
          allowUpdates: true
          draft: false
          prerelease: false
